### ISSUE TITLE
retro env

### ISSUE THREAD

**Issue by hlsafin** [michaelnny/deep_rl_zoo#1]
I'm sort of a newbie, how can I replace the atari env so that it supports retro env?

**Comment by michaelnny** [comment]
Hi, I've never played with retro env before, but I looked at their document, it seems like there are build like gym env.
https://retro.readthedocs.io/en/latest/getting_started.html#create-a-gym-environment

Anyway, the code responsible for interacting with the env is inside the module main_loop.py, mainly the function run_loop.

`while True:  # For each episode.
        t = 0
        agent.reset()
        # Think reset is a special 'aciton' the agent take, thus given us some 'zero' reward, and new s_t
        observation = env.reset()
        reward = 0.0
        done = False
        first_step = True

        while True:  # For each step in the current episode.
            timestep_t = types_lib.TimeStep(observation=observation, reward=reward, done=done, first=first_step)
            a_t = agent.step(timestep_t)
            yield env, timestep_t, agent, a_t

            t += 1
            a_tm1 = a_t

            observation, reward, done, _ = env.step(a_tm1)
            first_step = False

            if done:
                # if we don't add additonal step to agent, with our way of construct the run loop,
                # the done state and reward will never be added to replay
                timestep_t = types_lib.TimeStep(observation=observation, reward=reward, done=done, first=first_step)
                unused_a = agent.step(timestep_t)  # noqa: F841
                yield env, timestep_t, agent, None
                break

`

Maybe you can start from there if you want to adapt the code to support other env. You may also need to pay attention to the Python typing annotation, since we use that almost everywhere.

**Comment by hlsafin** [comment]
Okay, I'll give this a shot, my next question is a bit different and I can just ask it here. Let's say I have access to 8 gpu and 256 cpu/worker. How can I get the most out of these resources running R2D2 using all the gpu and cpu. I know it uses the cpu for each env, but does it utilize all the gpus or just a single one?

**Comment by michaelnny** [comment]
It's possible to use GPU for actors as well, you just need to adapt the code for your setup, for example for R2D2, check the code at 'r2d2.run_atari.py'
https://github.com/michaelnny/deep_rl_zoo/blob/c3527973d076f61ea4d8b85aadd0fc366d4a25e9/deep_rl_zoo/r2d2/run_atari.py#L195

By default,  actors and learner are using the same device, you can adjust the list for your machine and GPUs.
`actor_devices = [runtime_device] * FLAGS.num_actors`

But just to inform you that the current code only supports training on a single machine, not support distributed training. And I'm made some improvements to the code recently, you may want to download the latest code.

**Comment by michaelnny** [comment]
Yes, you need to change the code which I pointed in above comment. We're not sure if there's any issue with running on multiple GPUs, since we didn't test on that kind of setup yet. But you can try and send us feedback.

**Comment by hlsafin** [comment]
Okay, sweet. Also, I am currently trying to replicate the r2d2 paper, it seems like I'm not getting good results, what are some hyperparameters to use for games like Solaris and Montezuma's Revenge for hard exploration environments?

**Comment by michaelnny** [comment]
I believe R2D2 was not indent to solve those hard exploration games. You can try Agent57 or NGU agents, which are based on R2D2 but add intrinsic reward modules. We only tested our Agent57 on Pong, not those hard to explore games. 
Note, these types of agents (Agent57 and NGU) are much slower than R2D2 due to the episodic reward module.

**Comment by hlsafin** [comment]
That's true, R2D2 doesn't do as well as NGU and Agent57, but I am trying trying to get the similar scores they got on their paper for Solaris.
