### ISSUE TITLE
Quickly eats up memory, R2D2

### ISSUE THREAD

**Issue by hlsafin** [michaelnny/deep_rl_zoo#4]
I'm not exactly sure what I am doing wrong here, I have replay_buffer size at 1e6, but I also have memory size of 1T with a A100 gpu, with only 8 actors running. It quickly fills up my memory (my vram is good), even when I do half of the replay_buffer. Can you give me a good parameter so I can start testing R2D2? Thank you

**Comment by michaelnny** [comment]
The R2D2 agent (and NGU, Agent57) stores unrolled transition sequence instead of a single transition in the replay buffer. The total transitions one unroll have is equal to burn_in + unroll_length + 1. So if you're using the default configuration burn_in=40 and unroll_length=80, that means for every entry in the replay we have 40 + 80 + 1=121 transitions.

Multiple that by 1e6 and you get a really huge number. For start, I suggest you can first set it to 5000-10000 (depending on the setup). You can then try to gradually increase the size to see if that can improve the performance of the agent.

**Comment by hlsafin** [comment]
wow! that's very memory intensive! Okay, I have a few questions then. 
What does that +1 represent? Last reward? Last action? Because in the paper it was just burn_in+unroll_length, no?

Also, I am doing frame stacking of 4, so does this mean each unrolled transition consists of 4(frame_stack)*40(burn_in)*80(unroll_length)(84))(84)(heightxwidth_grayscale) = 4*40*80*84*84=90_316_800? Is my math correct here?

Also, another question, if I have access to multiple gpus, How can I expedite the training by using those gpus as well instead of just one?

**Comment by michaelnny** [comment]
Question 1:
The plus 1 is just for easy computation when we update the network parameters, since the network takes input some additional data other than the environment state. But it's not a big deal.

Question 2:
Well I don't fully get the intuition behind your calculation, here's how I would do that (we're using channel last in this case):
A single state image would be (apply grayscale and frame stack=4): 84 x 84 x 4 # [width, height, channel]
We have a time span of 40 + 80=120 state images for a single unroll transition: 120 x 84 x 84 x 4  # [time, width, height, channel]

You see we have a new time dimension now, it's important we keep the order of these images, since it represents what happened over the course of these (40 + 80) sequences. And we don't want to change the dimension of the frames either. During training a batch of sample unroll transitions will actually be [batch size, time, width, height, channel]. And we'd merge the batch and time dimensions before feed into the convolutional neural networks.
https://github.com/michaelnny/deep_rl_zoo/blob/b1ddf4a7ccb3c8c8960e7cad651f91e735b14702/deep_rl_zoo/networks/dqn.py#L948

Question 3:
You can try to assign different GPU to the actors which in theory will at least speed up the process of actors generate training samples. However I've never fully tested that since I don't have multiple GPUs on my PC.
https://github.com/michaelnny/deep_rl_zoo/blob/b1ddf4a7ccb3c8c8960e7cad651f91e735b14702/deep_rl_zoo/r2d2/run_atari.py#L198

Question 4:
Right now the code does these work, notice step 1 and step 2 are running at the same time, while step 3 and 4 are running in sequential order. You can find the details in the main_loop.py module.

`For every iteration:
        1. Run each actor for some steps (each actor will run num_train_frames steps) to generate transitions and send to the learner (replay buffer) on-the-fly;
        2. The learner will repeatedly sample transitions from the replay to update network parameters until all actors work are done;
        3. Create checkpoint files
        4. Run some evaluation steps (if num_eval_frames > 0) with a separate evaluation actor
`

**Comment by hlsafin** [comment]
First of all, thank you for your wonderful detailed response to my questions. I did make a mathematical error, but it should have been 120 x 84 x 84 x 4. 

I will try to work on implementing multiple GPUS and hopefully that speeds things up a bit and maybe integrate the environment to envpool, since that environment runs faster.

Maybe the final question, haha. In the R2D2 paper, they stated that they fed the last_reward and last_action to the LSTM, but from your code, I see that you only fed in the last action but not the last reward, how come? 

![image](https://user-images.githubusercontent.com/36808133/188212761-2c9d76b0-22bf-4933-9e97-d796f2c23406.png)
![image](https://user-images.githubusercontent.com/36808133/188212817-4dba82a7-6dc0-4815-9a4a-193bde40f0c3.png)

**Comment by emtiazsamad** [comment]
Hello, I am having some issues running r2d2 on the cartpole environment with anymore than 6 actors (and a batch size of 32). I am working on a multi-gpu environment with 6 Rtx 2080s 8G, so I am running out of memory. I have experimented with different batch sizes and actors however I am unable to run more than 6 actors despite reducing the batch size significantly. I am finding it difficult to use multiple GPUs and was wondering if anyone has found a solution. Thanks in advance!
